# TODO WRITEME

!obj:pylearn2.train.Train {
    dataset: &train !obj:gtzan.GTZAN_On_Memory {
        which_set: "train",
        window_size: 2048,
    },
    model: !obj:pylearn2.models.mlp.MLP {
        batch_size: 10,
        input_space: !obj:pylearn2.space.Conv2DSpace {
            shape: [512, 623],
            num_channels: 1,
        },
        layers: [
                    !obj:pylearn2.models.mlp.ConvRectifiedLinear {
                        layer_name: 'h2',
                        output_channels: 2,
                        irange: .05,
                        kernel_shape: [512, 5],
                        # W_lr_scale: .01,
                        # kernel_stride: [1, 5],
                        pool_shape: [1, 8],
                        pool_stride: [1, 4],
                        max_kernel_norm: 1.9365,
                    },
                    !obj:pylearn2.models.mlp.Softmax {
                        max_col_norm: 1.9365,
                        layer_name: 'y',
                        istdev: .05,
                        n_classes: 10
                    }
                ],
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        learning_rate: .01,
        # learning_rule: !obj:pylearn2.training_algorithms.learning_rule.RMSProp {},
        monitoring_dataset:
            {
                'train' : *train,
                'valid' : !obj:gtzan.GTZAN_On_Memory {
                            which_set: "valid",
                            window_size: 2048,
                          },
                'test'  : !obj:gtzan.GTZAN_On_Memory {
                            which_set: "test",
                            window_size: 2048,
                          }
            },
        cost: !obj:pylearn2.costs.cost.SumOfCosts {
            costs: [
                !obj:pylearn2.costs.mlp.Default {},
                !obj:pylearn2.costs.mlp.L1WeightDecay {
                    coeffs: { 'h2': 0.9 },
                }
            ]
        
        },
        # cost: !obj:pylearn2.costs.mlp.dropout.Dropout {
        #     input_include_probs: { 'h2' : .1 },
        #     input_scales: { 'h2' : 1.01 }
        # },
        termination_criterion: !obj:pylearn2.termination_criteria.MonitorBased {
            channel_name: "train_y_misclass",
            prop_decrease: 0.01,
            N: 20
        },
        # termination_criterion: !obj:pylearn2.termination_criteria.EpochCounter {
        #     max_epochs: 5000,
        # },
    },
    extensions: [
        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'valid_y_misclass',
             save_path: "${PYLEARN2_TRAIN_FILE_FULL_STEM}_best.pkl"
        },
    ],
    save_freq: 1
}
